# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'DDKeyPathChannelDemo' do
  pod 'DDKeyPathChannel', :path=>'../'
end
target 'DDKeyPathChannelDemoTests' do
  pod 'DDKeyPathChannel', :path=>'../'
end
